### ISSUE TITLE
Arquivos .json da pasta Script estão faltando

### ISSUE THREAD

**Issue by guionardo** [felipemarcelorocha/AsterixBrewery#1]
Olá.

No seu README.md consta que deve ser populado o MongoDB com dados dos arquivos JSON. 
Mas eles não estão no repositório.

**Comment by felipemarcelorocha** [comment]
Olá Guionardo,

Ao realizar o download do projeto, os arquivos estão na pasta "Scripts" abaixo da solution abrindo o projeto no visual studio.
Mesmo assim adicionei os arquivos dentro da pasta INFRA > Scripts.]

Obrigado.
